### ISSUE TITLE
material-ui 的导入方式需要改进

### ISSUE THREAD

**Issue by wangshijun** [blocklet/nft-store#13]
类似下面这种导入方式不推荐：

```
import {
  Container,
  Paper,
  Popper,
  ClickAwayListener,
  MenuList,
  MenuItem,
  Button,
  Box,
  Typography,
} from '@material-ui/core';
```

因为会把整个 package 导进来，前端代码导入 component 时请按需导入，否则打出来的包会很大

**Comment by LancelotLewis** [comment]
@wangshijun 
通过对比，发现两种方式打包后的体积相差 56kb，压缩后相差 20.5kb，包含的改动包括`@material-ui/core`和`@material-ui/icons`两个库，可得结果为使用顶层导入的方式在一定程度上增加了打包后的体积，但不是将整个 package 导入，

结论：虽然有 tree-shaking 协助，但体积还是大了一些，优先还是使用分开导入的形式

完整的`@material-ui/core` 体积为（https://cdn.jsdelivr.net/npm/@material-ui/core@4.11.3/umd/material-ui.production.min.js）：
![image](https://user-images.githubusercontent.com/8749615/113107543-a2abf600-9236-11eb-8d3f-5ccb742dbb60.png)

完整的`@material-ui/icons`体积为（https://cdn.jsdelivr.net/npm/@material-ui/icons@4.11.2/index.min.js）：
![image](https://user-images.githubusercontent.com/8749615/113107723-d38c2b00-9236-11eb-9764-cf1eb5481c70.png)




使用顶层导入：
![image](https://user-images.githubusercontent.com/8749615/113094747-d54cf300-9224-11eb-976c-8ff0a7c0321d.png)

使用路径导入：
![image](https://user-images.githubusercontent.com/8749615/113095458-0b3ea700-9226-11eb-852a-6ebaad5d843e.png)

控制台输出对比：
![image](https://user-images.githubusercontent.com/8749615/113095562-3a551880-9226-11eb-9cd0-9ea2cb90d921.png)
