### ISSUE TITLE
支付前检查用户余额是否足够

### ISSUE THREAD

**Issue by LancelotLewis** [blocklet/nft-store#15]

**Comment by LancelotLewis** [comment]
有两种用户场景：
- 用户未登录的时候，无法通过提前检查余额确认是否有足够的钱去购买
- 用户在登录的状态下，可以在进入购买页面之前做一个余额是否充足的判断

在场景二中，如果能有一个方式去提示用户当前的余额会更好

**Comment by wangshijun** [comment]
这个建议在钱包里面做，而不是在 store 里面做，钱包应该足够只能判断用户是否有足够的余额来支付，如果当前账户余额不够，那就用 delegation

https://github.com/ArcBlock/ocap-js/issues/109
