### ISSUE TITLE
当 NFT 详情页的数据没有加载完成时，点击”立即购买“会导致后面的 API 请求超时报错

### ISSUE THREAD

**Issue by polunzh** [blocklet/nft-store#21]
我发现当详情页的数据没有加载完成时，点击”立即购买“后，url 地址中会没有 nft did, 这就会导致调用 factory item 接口的 address 是 undefined，然后引发超时错误。

可以在 https://launcher.staging.arcblock.io/store/?__bv__=1.3.5&__blang__=zh 站点复现该错误。

页面没有加载完成:
![image](https://user-images.githubusercontent.com/4244426/113401541-189a9380-93d6-11eb-9848-7a893c1f4ee0.png)

没有 nft did 的url:
![image](https://user-images.githubusercontent.com/4244426/113401900-bdb56c00-93d6-11eb-870f-ff8f84214390.png)

没有 nft did 的 API 请求:
![image](https://user-images.githubusercontent.com/4244426/113401949-d6be1d00-93d6-11eb-92c5-6643c710bf8c.png)

**Comment by polunzh** [comment]
这里还有个问题是，如果这个非法的 API 请求 (https://launcher.staging.arcblock.io/store/api/factory/item?address=undefined) 会导致超时，而不是直接返回 500 的错误。
这个 API 会在服务端触发两个错误，一个是 NFT Store 自身的，另外是 @abtnode/service-loader 的错误，现在不确定这个超时的问题是不是 NFT Store 自己引起的:

NFT Store 的错误:
![image](https://user-images.githubusercontent.com/4244426/113402290-5d72fa00-93d7-11eb-8faa-4d88f6b940e0.png)

@abtnode/service-loader 的错误:
![image](https://user-images.githubusercontent.com/4244426/113402327-6c59ac80-93d7-11eb-9cbe-b7e743a9d38e.png)

**Comment by LancelotLewis** [comment]
- 在页面中使用`skeleton`效果补充loading效果显示，确保不会在loading过程中点击到功能按钮
- 服务端增加`express-async-errors`用于捕获`express`全局的`Promise uncaught`错误，服务器产生错误时，会直接返回500，而不是一直等待直到超时

**Comment by LancelotLewis** [comment]
@abtnode/service-loader 的相关错误有待跟进
