### ISSUE TITLE
在 详情页 和 购买页，如果当前的 factory address 在链上不存在，或者是无权限展示该 factory 的处理

### ISSUE THREAD

**Issue by LancelotLewis** [blocklet/nft-store#30]
目前的 NFT Store 在理论上能展示链上任意存在的 factory，不确定会带来什么副作用，所以需要判断是否加以限制，使 NFT Store仅展示对应 ownerAddress 下或是 config api 中有配置的 factory
@wangshijun

**Comment by wangshijun** [comment]
个人建议的判断逻辑：

- 如果 Store 配置了 FactoryOwner 或者 ConfigAPI，需要检查当前 factory 是否在白名单内
- 如果 Store 没任何配置，不用检查 factory 在白名单内
- 然后确保 factory 确实存在于链上，对于不在链上的需要有友好的报错
