### ISSUE TITLE
[UX] 详情页和购买页布局优化

### ISSUE THREAD

**Issue by LancelotLewis** [blocklet/nft-store#31]
可以作为参考
![image](https://user-images.githubusercontent.com/8749615/114184133-0ccf4400-9977-11eb-9a7a-c90ae506de03.png)

**Comment by wangshijun** [comment]
购买页面弹窗最好告诉用户 factory.title

![image](https://user-images.githubusercontent.com/719985/114481373-01aa3b80-9c37-11eb-91c2-68de7e117a38.png)

**Comment by LancelotLewis** [comment]
@wangshijun 目前 NFT Store 只有一些简单的信息用于描述 Factory，以后是否会考虑增加一个类似于“商品详情”的字段，能够像展示一个商品一样去展示一个 Factory
