### ISSUE TITLE
iPhone 上 responsive UI一些细节不好 导致卷滚

### ISSUE THREAD

**Issue by mave99a** [blocklet/nft-store#45]
![E342C813-40FC-44C1-92AF-EEDB77DEAA53](https://user-images.githubusercontent.com/41923/114655673-85990d80-9ca1-11eb-9927-aa401400a7af.png)

header 文字太多 菜单没有收起 可能没有使用对我们ux lib？

**Comment by LancelotLewis** [comment]
> ![E342C813-40FC-44C1-92AF-EEDB77DEAA53](https://user-images.githubusercontent.com/41923/114655673-85990d80-9ca1-11eb-9927-aa401400a7af.png)
> 
> header 文字太多 菜单没有收起 可能没有使用对我们ux lib？

#20 
对，这个项目还没有做移动端适配，会尽快处理
