### ISSUE TITLE
server 启动的时候需要获取一次 chainConfig，暂时需要用于显示 主 token 的 symbol

### ISSUE THREAD

**Issue by LancelotLewis** [blocklet/nft-store#9]

**Comment by LancelotLewis** [comment]
可以使用服务端做一个本地数据库用于存储项目的一些配置项，一方面能够完成存储 主 token 相关信息的需求，另一方面能增加环境变量配置的不足，后续还能为个性化配置 NFT Store 提供基础。

@wangshijun

**Comment by wangshijun** [comment]
不变的链上信息可以考虑做个简单的 memory cache，不用持久化存储。

**Comment by LancelotLewis** [comment]
使用一个全局的变量做数据缓存， chainConfig 仅在被需要时才请求一次，之后都从缓存中返回数据

**Comment by LancelotLewis** [comment]
#17
